### ISSUE TITLE
I think something is wrong here

### ISSUE THREAD

**Issue by PUDGE133** [iRebbok/RemotePermissionCard#1]
Or you made a mistake and entered the wrong numbers in the wiki. Or your plugin is really conceived not according to the standard list of items, but in its own way.
https://github.com/iRebbok/RemotePermissionCard/wiki/CList-DList-PDict-PList#clist-card-list
Item List:
ITEM#000 - Janitor Keycard
ITEM#001 - Scientist Keycard
ITEM#002 - Major Scientist Keycard
ITEM#003 - Zone Manager Keycard
ITEM#004 - Guard Keycard
ITEM#005 - Senior Guard Keycard
ITEM#006 - Containment Engineer Keycard
ITEM#007 - MTF Lieutenant Keycard
ITEM#008 - MTF Commander Keycard
ITEM#009 - Facility Manager Keycard
ITEM#010 - Chaos Card
ITEM#011 - 05 Card
ITEM#012 - Radio
ITEM#013 - Com15 Pistol
ITEM#014 - Medkit
ITEM#015 - Flashlight
ITEM#016 - MicroHID
ITEM#017 - Coin
ITEM#018 - Cup
ITEM#019 - Weapon Manager Tablet
ITEM#020 - Epsilon-11 Standard Rifle
ITEM#021 - P-90 
ITEM#022 - Epsilon ammo
ITEM#023 - MP7
ITEM#024 - Logicer
ITEM#025 - Grenade
ITEM#026 - Flash Grenade
ITEM#027 - Detainer
ITEM#028 - MP7/Logicer ammo
ITEM#029 - Pistol/P90 ammo

**Comment by iRebbok** [comment]
The plugin implements its ID in relation to the cards.

**Comment by PUDGE133** [comment]
If I change the access rights to the doors, then SCP cannot open the door. You also forgot about bypass.
