### ISSUE TITLE
Where is NUKE_ACC?

### ISSUE THREAD

**Issue by PUDGE133** [iRebbok/RemotePermissionCard#2]
https://github.com/iRebbok/RemotePermissionCard/wiki/CList-DList-PDict-PList#plist-permission-list

**Comment by iRebbok** [comment]
https://i.imgur.com/rVcXcZj.png
If you will look closely, you will not find here any 'NUKE_ACC'. Otherwise, let SMOD developers know, and only then will I add It to my plugin.
