### ISSUE TITLE
You forgot to add...

### ISSUE THREAD

**Issue by PUDGE133** [iRebbok/RemotePermissionCard#3]
https://github.com/iRebbok/RemotePermissionCard/wiki/CList-DList-PDict-PList#clist-card-list
You forgot to add number 12 - hand SCP(I mean, for example, I need to control which doors SCP objects are allowed to open.)
https://github.com/iRebbok/RemotePermissionCard/wiki/CList-DList-PDict-PList#pdict-permission-dictionary
You forgot to add boxes with electric generators
https://github.com/iRebbok/RemotePermissionCard/wiki/CList-DList-PDict-PList#dlist-door-list
You forgot to add boxes with electric generators

**Comment by iRebbok** [comment]
I didn't forget to add that, lol. It will be with the next version if you need it.
Generators are not a door. This is a completely different event, it will also be added in the next version.
